<div class="container">
   
        <div class="row">
             <form class="formOrganizacion">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Nombre Organizaci&oacute;n</label>
                    <input type="text" id="txt_nombreOrganizcion" class="form-control"> 
                </div>
                
           
            </div>
                  <div class="col-md-7">
                <div class="form-group">
                   
                    <button class="btn btn-success">Crear Nueva Organizaci&oacute;n</button>
                </div>
                
           
            </div>
           </form>    

</div>
</div>