<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h3 class="page-header"></h3>
        
            <a class="btn btn-primary" id="btnAgregar"  <a data-toggle="modal" href="#myModal" onClick="Sistema.prototype.procesoEnviaForm('<?php echo BASE_URL ?>sistema/abreOrganizacion', 'Nueva Organización')" >
            <div class="panel-body">
                Agregar una nueva organizaci&oacute;n <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </div>
            </a>
 
        </div>
    </div>
   
</div>